---
# the location of the nodepool config file source
nodepool_file_nodepool_yaml_src: "{{ lookup('env', 'WORKSPACE') }}/rpc-gating/nodepool/nodepool-config.yml"

# which version of nodepool to clone
nodepool_git_version: 3de0b20faa6f90437eb62c56ec23c59c6e15b5fa # HEAD of 'master' as of 20 Mar 2018

# Ensure nodepool is installed under python3
nodepool_pip_executable: pip3

# which version of diskimage-builder to clone
diskimage_builder_git_version: "2.12.1" # Current release as of 22 Mar 2018

# where to source the diskimage-builder elements from
diskimage_builder_elements_src: "{{ lookup('env', 'WORKSPACE') }}/rpc-gating/nodepool/elements"

# enable installation of zookeeper from apt packages
zookeeper_debian_apt_install: yes

# set the host group for zookeeper's cluster
zookeeper_hosts: "{{ groups['nodepool_server'] }}"

# Additional Hosts which can access the zookeeper cluster
zookeeper_access_list:
  - 74.205.74.100 # CIT Jenkins master (NAT)

# log rotation
logrotate_configs:
  - name: nodepool-builder
    log: /var/log/nodepool/builder-debug.log /var/log/nodepool/nodepool-builder.log
    options:
      - compress
      - missingok
      - rotate 7
      - daily
      - notifempty
  - name: nodepool-launcher
    log: /var/log/nodepool/launcher-debug.log /var/log/nodepool/nodepool-launcher.log
    options:
      - compress
      - missingok
      - rotate 7
      - daily
      - notifempty
  - name: zookeeper
    log: /var/log/zookeeper/zookeeper.log
    options:
      - compress
      - missingok
      - rotate 7
      - daily
      - notifempty
