---
gating_overrides_file: "{{ lookup('env', 'WORKSPACE') }}/user_zzz_gating_variables.yml"
gating_overrides:
  apply_security_hardening: false
  maas_fqdn_extension: ".{{ lookup('env', 'NODE_NAME') }}"
  memory_used_percentage_warning_threshold: 99.0
  memory_used_percentage_critical_threshold: 99.5
  net_max_speed: 1000
  lb_name: "{{ lookup('env', 'NODE_NAME') }}"
  # NOTE(mattt): This functionality is currently broken on multi-node
  #              deployments, disabling until this is addressed in
  #              openstack-ansible-os_cinder
  cinder_service_backup_program_enabled: false
  maas_external_ip_address: "{{ ansible_default_ipv4.address }}"
  tempest_testr_opts:
    - '--concurrency 3'
  tempest_run_tempest_opts: []
  staging_host: repo-infra_hosts
