---
- parameter:
    name: single_use_slave_params
    parameters:
      - string:
          name: REGION
          default: "IAD"
      - string:
          name: FLAVOR
          default: "performance2-15"
      - string:
          name: IMAGE
          default: "{IMAGE}"
      - string:
          name: INSTANCE_NAME
          default: AUTO
          description: |
            Set instance name or "AUTO" to have it generated based on job
            name and build number. Beware the 63 char container name limit
            as container names includes the host name.

- parameter:
    name: rpc_params
    parameters:
      - string:
          name: "RPC_REPO"
          default: "https://github.com/rcbops/rpc-openstack"
      - string:
          name: "RPC_BRANCH"
          default: "{RPC_BRANCH}"
      - string:
          name: "DEPLOY_CEPH"
          default: "{DEPLOY_CEPH}"
      - string:
          name: "DEPLOY_ELK"
          default: "{DEPLOY_ELK}"

- parameter:
    name: rpc_gating_params
    parameters:
      - string:
          name: RPC_GATING_REPO
          default: "https://github.com/rcbops/rpc-gating"
      - string:
          name: RPC_GATING_BRANCH
          default: "master"

- parameter:
    name: tempest_params
    parameters:
      - string:
          name: "TEMPEST_TEST_SETS"
          default: "scenario defcore cinder_backup"
          description: |
            Test sets (space seperated). Test sets are defined in
            https://github.com/openstack/openstack-ansible-os_tempest/blob/master/templates/openstack_tempest_gate.sh.j2
      - string:
          name: "RUN_TEMPEST_OPTS"
          default: "--serial"
          description: |
            Options to pass to run_tempest.sh via openstack_tempest_gate.sh
            Note that both are deprecated and will be replaced in future.
