#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# The bash environment variables used here should be coming from
# the environment.d script.

# Add the base repo source
sudo bash -c "cat << EOF >${TARGET_ROOT}/etc/apt/sources.list
deb ${DIB_DISTRIBUTION_MIRROR} ${DIB_RELEASE} ${DIB_DEBIAN_COMPONENTS//,/ }
EOF"

# Make sure that the sources.list.d directory exists
# (it was removed by the debootstrap element)
sudo bash -c "mkdir ${TARGET_ROOT}/etc/apt/sources.list.d"

# Add the RPC-O apt repo source
sudo bash -c "cat << EOF >${TARGET_ROOT}/etc/apt/sources.list.d/rpco.list
deb ${RCBOPS_REPO_APT_URL} ${RPC_RELEASE}-${DIB_RELEASE} main
EOF"

sudo mount -t proc none ${TARGET_ROOT}/proc
sudo mount -t sysfs none ${TARGET_ROOT}/sys
trap "sudo umount ${TARGET_ROOT}/proc; sudo umount ${TARGET_ROOT}/sys" EXIT

# Install the RPC-O apt repo key
sudo bash -c "curl --silent --fail ${RCBOPS_REPO_KEY_URL} |\
              sudo chroot ${TARGET_ROOT} apt-key add -"

apt_get="sudo chroot ${TARGET_ROOT} /usr/bin/apt-get" # dib-lint: safe_sudo

# Need to update to retrieve the signed Release file
$apt_get update

$apt_get clean
$apt_get dist-upgrade -y

$apt_get install -y busybox sudo
