---
- name: Install dependencies
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 600
  register: pkgs
  until: pkgs|success
  retries: 3
  with_items:
    - ifenslave-2.6
    - bridge-utils
    - vlan

- name: Enable networking modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - bonding
    - 8021q

- name: Ensure module persistance
  lineinfile:
    dest: /etc/modules
    state: present
    regexp: "^{{ item }}"
    line: "{{ item }}"
  with_items:
    - bonding
    - 8021q

- name: Ensure /etc/network/interfaces.d exists
  file:
    path: /etc/network/interfaces.d
    state: directory
    owner: root
    mode: 0655
  when: networking is defined

- name: Setup root interface
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    mode: 0644
  when: networking is defined

- name: Setup additional interfaces
  template:
    src: interface.j2
    dest: /etc/network/interfaces.d/{{ item.name }}.cfg
    mode: 0644
  with_items: "{{ networking|default([]) }}"

- name: Enable all defined interfaces
  command: ifup --all
  when: enable_interfaces
