---
lab_name: fcfs-iad3-storage01

networking:
  - name: lo
    type: loopback
  - name: p6p1
    type: manual
    directives:
      - "bond-master bond0"
      - "bond-primary p6p1"
  - name: p7p1
    type: manual
    directives:
      - "bond-master bond0"
  - name: em3
    type: static
    directives:
    - "netmask {{ ansible_em3.ipv4.netmask }}"
    - "post-up ip route add 10.191.192.0/18 via 10.136.93.65 dev em3"
    - "address {{ ansible_em3.ipv4.address }}"
  - name: p6p2
    type: manual
    directives:
      - "bond-master bond1"
      - "bond-primary p6p2"
  - name: p7p2
    type: manual
    directives:
      - "bond-master bond1"
  - name: bond0
    type: static
    directives:
      - "bond-slaves none"
      - "bond-mode active-backup"
      - "bond-miimon 100"
      - "bond-downdelay 200"
      - "bond-updelay 200"
      - "address {{ ansible_default_ipv4.address }}"
      - "netmask {{ ansible_default_ipv4.netmask }}"
      - "gateway {{ ansible_default_ipv4.gateway }}"
      - "dns-nameservers 69.20.0.164 69.20.0.196"
      - "dns-search fcfs-iad3-storage-1.rackspace.com"
  - name: bond1
    type: manual
    directives:
      - "bond-slaves none"
      - "bond-mode active-backup"
      - "bond-miimon 100"
      - "bond-downdelay 250"
      - "bond-updelay 250"
  - name: bond0.694
    type: manual
    directives:
      - "vlan-raw-device bond0"
  - name: bond0.465
    type: manual
    directives:
      - "vlan-raw-device bond0"
  - name: bond1.885
    type: manual
    directives:
      - "vlan-raw-device bond1"
  - name: br-mgmt
    type: static
    directives:
      - "bridge_stp off"
      - "bridge_waitport 0"
      - "bridge_fd 0"
      - "bridge-ports bond0.694"
      - "address 172.29.236.{{ member_number }}/22"
      - "dns-nameservers 69.20.0.164 69.20.0.196"
  - name: br-storage
    type: static
    directives:
      - "bridge_stp off"
      - "bridge_waitport 0"
      - "bridge_fd 0"
      - "bridge_ports bond0.465"
      - "address 172.29.244.{{ member_number }}/22"
  - name: br-replication
    type: static
    directives:
      - "bridge_stp off"
      - "bridge_waitport 0"
      - "bridge_fd 0"
      - "bridge_ports bond1.885"
      - "address 192.168.1.{{ member_number }}/22"
  - name: br-snet
    type: static
    directives:
      - "bridge_stp off"
      - "bridge_waitport 0"
      - "bridge_fd 0"
      - "address 172.29.248.1"
      - "netmask 255.255.252.0"
