---
lab_name: fcfs-iad3-lab06
config_prefix: openstack
repo_dir: openstack-ansible

user_config:
    container_cidr: 172.16.80.0/22
    tunnel_cidr:  172.16.88.0/22
    storage_cidr:  172.16.84.0/22
    used_ips:
        - "172.16.80.1,172.16.80.15"
        - "172.16.80.73,172.16.80.127"
        - "172.16.88.73,172.16.88.127"
        - "172.16.84.73,172.16.84.127"
    internal_lb_vip_address: 172.16.80.10
    external_lb_vip_address: 204.232.135.164
    tunnel_bridge: br-vxlan
    container_bridge: br-mgmt
    lb_name: 578305-fcfs-lb1.rpc.rackspace.com
    networking:
        - name: container
          bridge: br-mgmt
          container_bridge: br-mgmt
          container_interface: eth1
          container_type: veth
          ip_from_q: container
          type: raw
          is_ssh_address: true
          is_container_address: true
          group_binds:
            - all_containers
            - hosts
        - name: provider
          bridge: br-vlan
          container_interface: eth11
          container_type: veth
          type: vlan
          range: 235:235
          net_name: vlan
          group_binds:
            - neutron_linuxbridge_agent
        - name: tenant
          bridge: br-vxlan
          container_interface: eth10
          container_type: veth
          ip_from_q: tunnel
          type: vxlan
          range: 1:1000
          net_name: vxlan
          group_binds:
            - neutron_linuxbridge_agent
        - name: storage
          bridge: br-storage
          container_interface: eth2
          container_type: veth
          ip_from_q: storage
          type: raw
          group_binds:
            - glance_api
            - cinder_api
            - cinder_volume
            - nova_compute
            - swift_proxy

# tempest net config
tempest_public_provider_net:
  tempest_public_subnet_cidr: "10.16.84.0/24"
  tempest_public_subnet_gateway: "10.16.84.1"
  tempest_public_net_provider_type: vlan
  tempest_public_net_physical_type: vlan
  tempest_public_net_seg_id: 235
  tempest_public_router_external: True

tempest_private_net:
  tempest_private_subnet_cidr: "192.168.1.0/24"
  tempest_private_net_provider_type: "vxlan"
  tempest_private_net_seg_id: 1

# all swift configuration
swift_config:
  part_power: 8
  weight: 100
  min_part_hours: 1
  repl_number: 3
  region: 1
  storage_network: 'br-storage'
  drives:
    - name: sdc
    - name: sdd
  lv_size: 50G
  mount_point: /mnt
  account: "service:glance"
  mount_opts: 'noatime,nodiratime,nobarrier,logbufs=8,nobootwait'
  container: glance
  storage_policies:
    - name: gold
      index: 0
      default: True
    - name: silver
      index: 1
      repl_number: 3
      depreciated: True

# cinder configuration
cinder_storage:
  backends:
    lvm:
      volume_group: cinder-volumes
      volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
      volume_backend_name: LVM_iSCSI

# all networking interface configs
networking:
    - name: lo
      type: loopback
    - name: em3
      type: static
      directives:
      - "netmask {{ ansible_em3.ipv4.netmask }}"
      - "post-up ip route add 10.191.192.0/18 via 10.136.157.225 dev em3"
      - "address {{ ansible_em3.ipv4.address }}"
    - name: p3p1
      type: manual
      directives:
        - "bond-master bond0"
        - "bond-primary p3p1"
    - name: p4p1
      type: manual
      directives:
        - "bond-master bond0"
    - name: p3p2
      type: manual
      directives:
        - "bond-master bond1"
        - "bond-primary p3p2"
    - name: p4p2
      type: manual
      directives:
        - "bond-master bond1"
    - name: bond0
      type: static
      directives:
        - "bond-slaves none"
        - "bond-mode active-backup"
        - "bond-miimon 100"
        - "bond-downdelay 200"
        - "bond-updelay 200"
        - "address {{ ansible_default_ipv4.address }}"
        - "netmask {{ ansible_default_ipv4.netmask }}"
        - "gateway {{ ansible_default_ipv4.gateway }}"
        - "dns-nameservers 69.20.0.164 69.20.0.196"
        - "dns-search rpc.rackspace.com"
    - name: bond1
      type: manual
      directives:
        - "bond-slaves none"
        - "bond-mode active-backup"
        - "bond-miimon 100"
        - "bond-downdelay 250"
        - "bond-updelay 250"
    - name: bond0.232
      type: manual
      directives:
        - "vlan-raw-device bond0"
    - name: bond0.233
      type: manual
      directives:
        - "vlan-raw-device bond0"
    - name: bond1.234
      type: manual
      directives:
        - "vlan-raw-device bond1"
    - name: br-mgmt
      type: static
      directives:
        - "bridge_stp off"
        - "bridge_waitport 0"
        - "bridge_fd 0"
        - "bridge_ports bond0.232"
        - "address 172.16.80.{{ member_number }}/22"
        - "dns-nameservers 69.20.0.164 69.20.0.196"
    - name: br-vlan
      type: manual
      directives:
        - "bridge_stp off"
        - "bridge_waitport 0"
        - "bridge_fd 0"
        - "bridge_ports bond1"
    - name: br-vxlan
      type: static
      directives:
        - "bridge_stp off"
        - "bridge_waitport 0"
        - "bridge_fd 0"
        - "bridge_ports bond1.234"
        - "address 172.16.88.{{ member_number }}/22"
    - name: br-storage
      type: static
      directives:
        - "bridge_stp off"
        - "bridge_waitport 0"
        - "bridge_fd 0"
        - "bridge_ports bond0.233"
        - "address 172.16.84.{{ member_number }}/22"
    - name: br-snet
      type: static
      directives:
        - "bridge_stp off"
        - "bridge_waitport 0"
        - "bridge_fd 0"
        - "address 172.27.248.1/22"

# volume groups for cinder / swift
vgs:
    - name: cinder-volumes
      device:
        - /dev/sdb
