---
- parameter:
    name: instance_params
    parameters:
      - string:
          name: REGIONS
          default: "{REGIONS}"
          description: |
            CSV list of preferred regions, will be tried in a random order
      - string:
          name: FALLBACK_REGIONS
          default: "{FALLBACK_REGIONS}"
          description: |
            CSV list of regions that this job can run in. Any regions
            not contined in REGIONS will be used as fallbacks.
      - string:
          name: FLAVOR
          default: "{FLAVOR}"
      - string:
          name: IMAGE
          default: "{IMAGE}"
      - string:
          name: INSTANCE_NAME
          default: AUTO
          description: |
            Set instance name or "AUTO" to have it generated based on job
            name and build number. Beware the 63 char container name limit
            as container names includes the host name.
- parameter:
    name: jenkins_node_params
    parameters:
      - string:
          name: JENKINS_NODE_LABELS
          default: "{JENKINS_NODE_LABELS}"
          description: |
            Number of executors to start on each slave
      - string:
          name: JENKINS_NODE_EXECUTORS
          default: "{JENKINS_NODE_EXECUTORS}"
          description: |
            Number of executors to start on each slave
        # Bool param defaults are converted to lower case :(
        # https://review.openstack.org/#/c/473828/
      - bool:
          name: jenkins_node_exclusive
          default: "{jenkins_node_exclusive}"
          description: |
            Create slave in exclusive mode?
            An exclusive slave will only be used for jobs that specify its
            name or labels. A non exclusive node will run jobs that don't
            specify a name or label. eg common.shared_slave(){{}} blocks. Single use slaves
            should be exclusive, multi use slaves should not.
      - bool:
          name: allow_jenkins_sudo
          default: "{allow_jenkins_sudo}"
          description: |
            Grant the jenkins slave passwordless sudo. This is useful for
            single use slaves, but must not be set for long running
            slaves as it will allow jobs to pollute the build environment.


- parameter:
    name: rpc_repo_params
    parameters:
      - string:
          name: "RPC_REPO"
          default: "https://github.com/rcbops/rpc-openstack"
      - string:
          name: "RPC_BRANCH"
          default: "{RPC_BRANCH}"

- parameter:
    name: rpc_eng_ops_params
    parameters:
      - string:
          name: "RPC_ENG_OPS_REPO"
          default: "git@github.com:rcbops/rpc-eng-ops"
      - string:
          name: "RPC_ENG_OPS_BRANCH"
          default: "{RPC_ENG_OPS_BRANCH}"

- parameter:
    name: rpc_gating_params
    parameters:
      - string:
          name: RPC_GATING_BRANCH
          default: "master"
          description: |
            Version of rpc-gating. This is used when loading the rpc-gating
            groovy library, and when cloning RPC_GATING_REPO into each
            workspace. The clone source is always rcbops/rpc-gating.

- parameter:
    name: rpc_maas_params
    parameters:
      - string:
          name: "RPC_MAAS_REPO"
          default: "https://github.com/rcbops/rpc-maas"
      - string:
          name: "RPC_MAAS_BRANCH"
          default: "{RPC_MAAS_BRANCH}"

- parameter:
    name: standard_job_params
    parameters:
      - string:
          name: "SLAVE_TYPE"
          default: "{SLAVE_TYPE}"
          description: >
            Standard jobs can be run on different types of slave. The default
            for this parameter is set to "instance" for a compute instances. To
            use a Docker container set this parameter to "container".
        # we used to use choice for this, but choice doesn't take a default
        # parameter, so doesn't work with the way we pass in JJB variables.
      - string:
          name: "SLAVE_CONTAINER_DOCKERFILE_REPO"
          default: "{SLAVE_CONTAINER_DOCKERFILE_REPO}"
          description: >
            Choices: RE, PROJECT.
            This parameter, which defaults to "RE", determines where to look
            for the Dockerfile specified in SLAVE_CONTAINER_DOCKERFILE_PATH.
            "RE" searches within rpc-gating, and "PROJECT" searches within the
            project in test.
      - string:
          name: "SLAVE_CONTAINER_DOCKERFILE_PATH"
          default: "{SLAVE_CONTAINER_DOCKERFILE_PATH}"
          description: >
            This is the relative path of the Dockerfile to build from. This
            defaults to "./Dockerfile.standard_job".
      - string:
          name: "SLAVE_CONTAINER_DOCKERFILE_BUILD_ARGS"
          default: "{SLAVE_CONTAINER_DOCKERFILE_BUILD_ARGS}"
          description: >
            This is a list of space-separated build args to pass to docker
            build. This defaults to "BASE_IMAGE=ubuntu:16.04", which is
            specifically applicable to the "./Dockerfile.standard_job" in
            rpc-gating.

- parameter:
    name: phobos_params
    parameters:
      - string:
          name: GATEWAY
          default: from_creds
          help: |
            IP of Phobos VPN Gateway, if set to "from_creds", the gateway
            IP will be pulled from the Jenkins Creds Store
      - string:
          name: PING_HOST
          default: 172.20.4.10
          help: |
            Host that is only accessible via Phobos vpn, used to verify
            connectivity
