---
- parameter:
    name: instance_params
    parameters:
      - string:
          name: REGION
          default: "{REGION}"
      - string:
          name: FLAVOR
          default: "{FLAVOR}"
      - string:
          name: IMAGE
          default: "{IMAGE}"
      - string:
          name: INSTANCE_NAME
          default: AUTO
          description: |
            Set instance name or "AUTO" to have it generated based on job
            name and build number. Beware the 63 char container name limit
            as container names includes the host name.
- parameter:
    name: jenkins_node_params
    parameters:
      - string:
          name: JENKINS_NODE_LABELS
          default: "{JENKINS_NODE_LABELS}"
          description: |
            Number of executors to start on each slave
      - string:
          name: JENKINS_NODE_EXECUTORS
          default: "{JENKINS_NODE_EXECUTORS}"
          description: |
            Number of executors to start on each slave
        # Bool param defaults are converted to lower case :(
        # https://review.openstack.org/#/c/473828/
      - bool:
          name: jenkins_node_exclusive
          default: "{jenkins_node_exclusive}"
          description: |
            Create slave in exclusive mode?
            An exclusive slave will only be used for jobs that specify its
            name or labels. A non exclusive node will run jobs that don't
            specify a name or label. eg common.shared_slave(){{}} blocks. Single use slaves
            should be exclusive, multi use slaves should not.
      - bool:
          name: allow_jenkins_sudo
          default: "{allow_jenkins_sudo}"
          description: |
            Grant the jenkins slave passwordless sudo. This is useful for
            single use slaves, but must not be set for long running
            slaves as it will allow jobs to pollute the build environment.


- parameter:
    name: rpc_repo_params
    parameters:
      - string:
          name: "RPC_REPO"
          default: "https://github.com/rcbops/rpc-openstack"
      - string:
          name: "RPC_BRANCH"
          default: "{RPC_BRANCH}"

- parameter:
    name: osa_ops_params
    parameters:
      - string:
          name: OSA_OPS_REPO
          default: https://github.com/git-harry/openstack-ansible-ops
      - string:
          name: OSA_OPS_BRANCH
          default: 93ac83d3436fd078500d6fd85ec5078e357f4db4
      - string:
          name: DEFAULT_IMAGE
          default: "{DEFAULT_IMAGE}"
          description: Version of Ubuntu image to use for VMs (14.04.5 or 16.04.2)
      - string:
          name: DEFAULT_KERNEL
          default: "linux-image-4.4.0-66-generic"
          description: Ubuntu Kernel package to use for VMs (linux-image-4.4.0-66-generic, linux-image-3.13.0-34-generic, etc.)
      - bool:
          name: PARTITION_HOST
          default: true
          description: Enable partitioning of host data disk device
      - string:
          name: DATA_DISK_DEVICE
          default: "{DATA_DISK_DEVICE}"
          description: The data disk to use for VMs (if unset the largest unpartitioned device will be used)
      - string:
          name: MULTI_NODE_AIO_DIR
          default: "multi-node-aio"
          description: |
            The directory to trigger build.sh from
            Options:
              multi-node-aio
              multi-node-aio-xenial-ansible
      - string:
          name: "COMPUTE_NODES"
          default: "{COMPUTE_NODES}"
          description: "The number of compute nodes to deploy."
      - string:
          name: "VOLUME_NODES"
          default: "{VOLUME_NODES}"
          description: "The number of volume nodes to deploy."

- parameter:
    name: rpc_deploy_params
    parameters:
      - string:
          name: "DEPLOY_SWIFT"
          default: "{DEPLOY_SWIFT}"
          description: "Deploy Swift? yes/no"
      - string:
          name: "DEPLOY_CEPH"
          default: "{DEPLOY_CEPH}"
          description: "Deploy Ceph? yes/no"
      - string:
          name: "DEPLOY_ELK"
          default: "{DEPLOY_ELK}"
          description: "Deploy ELK? yes/no"
      - string:
          name: "DEPLOY_MAAS"
          default: "{DEPLOY_MAAS}"
          description: "Deploy and verify maas? yes/no"
      - string:
          name: "DEPLOY_IRONIC"
          default: "{DEPLOY_IRONIC}"
          description: "Deploy Ironic? yes/no"
      - text:
          name: "USER_VARS"
          default: "{USER_VARS}"
          description: "OSA/RPC USER_VARS to inject for this build"
      - string:
          name: "UPGRADE_FROM_REF"
          default: "{UPGRADE_FROM_REF}"
          description: "An tag/sha/ref to upgrade from"

- parameter:
    name: rpc_gating_params
    parameters:
      - string:
          name: RPC_GATING_BRANCH
          default: "master"
          description: |
            Version of rpc-gating. This is used when loading the rpc-gating
            groovy library, and when cloning RPC_GATING_REPO into each
            workspace. The clone source is always rcbops/rpc-gating.

- parameter:
    name: kibana_selenium_params
    parameters:
      - string:
          name: "KIBANA_SELENIUM_REPO"
          default: "https://github.com/rcbops-qe/kibana-selenium.git"
      - string:
          name: "KIBANA_SELENIUM_BRANCH"
          default: "{KIBANA_SELENIUM_BRANCH}"

- parameter:
    name: rpc_maas_params
    parameters:
      - string:
          name: "RPC_MAAS_REPO"
          default: "https://github.com/rcbops/rpc-maas"
      - string:
          name: "RPC_MAAS_BRANCH"
          default: "{RPC_MAAS_BRANCH}"

- parameter:
    name: generate_test_params
    parameters:
      - string:
          name: "GENERATE_TEST_NETWORKS"
          default: "{GENERATE_TEST_NETWORKS}"
      - string:
          name: "GENERATE_TEST_SERVERS"
          default: "{GENERATE_TEST_SERVERS}"
      - string:
          name: "GENERATE_TEST_VOLUMES"
          default: "{GENERATE_TEST_VOLUMES}"

- parameter:
    name: tigkstack_params
    parameters:
      - string:
          name: "DEPLOY_TELEGRAF"
          default: "{DEPLOY_TELEGRAF}"
      - string:
          name: "DEPLOY_INFLUX"
          default: "{DEPLOY_INFLUX}"
