---
- hosts: job_nodes
  connection: local
  gather_facts: False
  vars:
    cloud_name: "public_cloud"
  tasks:
    - name: Cleanup public cloud instance
      os_server:
        name: "{{ instance_name }}"
        state: absent
        cloud: "{{ cloud_name }}"
        region_name: "{{ rax_region }}"
        wait: yes
        timeout: 900
      delegate_to: localhost
