---
- hosts: job_nodes
  user: root
  tasks:
    - name: Destroy slave
      delegate_to: localhost
      shell: |
        cd  {{ lookup('env', 'WORKSPACE') }}/rpc-gating/playbooks
        . .venv/bin/activate
        pip install jenkinsapi
        python ../scripts/jenkins_node.py delete --name {{inventory_hostname}}
      when:
        - rax_metadata is not defined or (rax_metadata is defined and not rax_metadata.preserve|default(false)|bool)
