---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Get facts about servers with a given name
      local_action:
          module: rax_facts
          name: "{{ name }}"

    - name: Show IP of server with given name, fail if no such server exists in region
      debug: var=rax_accessipv4
      failed_when: rax_accessipv4 is undefined

    - name: Set ansible host to IP address of server with given name
      set_fact:
          ansible_host: "{{ rax_accessipv4 }}"

    - name: Add servers to job_nodes host group
      local_action:
        module: add_host
        hostname: "{{ name }}"
        ansible_host: "{{ rax_accessipv4 }}"
        ansible_user: root
        groupname: job_nodes

    - name: Wait for SSH to be available on host
      wait_for: port=22 host="{{ ansible_host }}"


- hosts: job_nodes
  user: root
  tasks:
    - name: Install apt packages
      apt:
        pkg: "{{ item }}"
        state: installed
        update_cache: yes
      with_items:
        - git
        - default-jre-headless
        - python-dev
        - python-pip
        - build-essential

    - name: Create Jenkins user
      user:
        name: jenkins
        home: /var/lib/jenkins
        shell: /bin/bash

    - name: Add RPC public keys to authorized_keys
      authorized_key: "user={{ item }} key='{{ lookup('file', lookup('env', 'WORKSPACE')+'/rpc-gating/keys/rcb.keys') }}' state=present"
      with_items:
        - root
        - jenkins

    - name: Set proper permissions for Jenkins home directory
      file:
        path: /var/lib/jenkins
        owner: jenkins
        group: jenkins
        recurse: yes

    - name: Set Jenkins user to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: 'jenkins'
        line: 'jenkins ALL=(ALL) NOPASSWD: ALL'

      # pip module didn't work here as it couldn't locate the virtualenv binary
    - name: Start slave
      delegate_to: localhost
      shell: |
        cd  {{ lookup('env', 'WORKSPACE') }}/rpc-gating/playbooks
        . .venv/bin/activate
        pip install jenkinsapi
        virtualenv --relocatable .venv
        python ../scripts/jenkins_node.py \
          create \
          --name {{inventory_hostname}} \
          --ip {{ansible_default_ipv4.address}} \
          --creds "SSH Creds for Jenkins instances in public cloud." \
          --labels single_use_slave
