---
# We need to target all hosts in the group first to gather facts,
# otherwise any tasks using the group host_vars will fail.
- name: Gather facts from required server groups
  hosts: "nodepool_server:statsd_server"
  gather_facts: no
  user: root
  tasks:
    - name: Wait for a successful connection
      wait_for_connection:
        connect_timeout: 2
        delay: 5
        sleep: 5
        timeout: 60

    - name: Gather facts
      setup:
        gather_subset: "!facter,!ohai"

- name: Setup statsd servers
  hosts: "statsd_server"
  gather_facts: no
  user: root
  vars:
    statsd_file_config_js_src: config.js.j2
    logrotate_configs:
      - name: statsd
        log: /var/log/statsd/statsd.log
        options:
          - compress
          - missingok
          - rotate 7
          - daily
          - notifempty
  tasks:
    - name: Install prerequisite distro packages
      apt:
        name:
          # requirement for cloning the repos
          # we install from
          - git
          # requirements for pip installs
          - gcc
          - libffi-dev
          - libssl-dev
          - python3-pip
          # requirements for ansible
          # TODO(odyssey4me):
          # Remove aptitude when we shift to using
          # ansible 2.4
          - aptitude
          - python3-apt
          - python3-minimal
        update_cache: yes
      register: install_packages
      until: install_packages | success
      retries: 5
      delay: 2

    - name: Configure firewall to allow nodepool cluster traffic (ipv4)
      ufw:
        rule: allow
        from_ip: "{{ hostvars[item].ansible_default_ipv4.address }}"
      with_items: "{{ groups['nodepool_server'] }}"

    - name: Setup statsd
      include_role:
        name: openstack.statsd

    - name: Restart statsd if the config file has changed
      service:
        name: statsd
        enabled: yes
        daemon_reload: yes
        state: restarted
      when:
        - statsd_file_config_js is defined
        - statsd_file_config_js is mapping
        - statsd_file_config_js | changed

    - name: Implement log rotation
      include_role:
        name: openstack.logrotate
